spring.application.name=task-tracker

spring.datasource.url=jdbc:postgresql://postgres-db:5432/task_tracker
spring.datasource.username=postgres
spring.datasource.password=postgres1$
spring.datasource.driver-class-name=org.postgresql.Driver
spring.mvc.throw-exceptions=true

spring.liquibase.change-log=classpath:/db/changelog/changelog-master.xml
spring.liquibase.enabled=true