# ?????? ?????????? Ryuk
ryuk.container.enabled=false
check.disable=true

# ?????????? ???? ????????
testcontainers.checks.disable=true

# ????????????? Docker ?????? ????????
docker.client.strategy=org.testcontainers.dockerclient.UnixSocketClientProviderStrategy